# Generated by Django 4.0 on 2021-12-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
