# Generated by Django 4.0 on 2021-12-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0003_remove_configref_save_date_candidate_website_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
